### ISSUE TITLE
Alveo U200 - compile

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/ResNet50-PYNQ#1]
Hi @quetric , @giunatale 

Changed Makefile for Alveo U200  compilation . Please let me know, what are the changes required to generate overlay for U200.

**Comment by quetric** [comment]
Hi @mahinlma 

Thank you for your interest. Given the architecture of the accelerator and the requirements for weights being on-chip, currently the accelerator is too large for the U200 (specifically, the U200 doesnt have enough memory). We're working on a solution but don't have a timeline for a U200 release yet. I'll keep this issue open though.

**Comment by mahinlma** [comment]
Thank you @quetric

**Comment by simplelins** [comment]
Hi， @quetric , @giunatale
what's different from resblock.tcl, inoutdma.tcl, preres.tcl, postres.tcl which do, and more, now is it ok for using this demo for Alveo U200 compilation. thanks!

**Comment by lloo099** [comment]
Hi, do u have an update on U200?

**Comment by quetric** [comment]
We don't support this network on u200. For a smaller imagenet accelerator that *may* fit the U200, see https://github.com/Xilinx/finn-examples - Mobilenet-v1
