### ISSUE TITLE
Make failed for U250

### ISSUE THREAD

**Issue by h-yuan** [Xilinx/ResNet50-PYNQ#2]
I made test on my local host step by step with instruction, when execute "make NET=w1a2_v1.0", it comes some error.
```
if [[ res2a = res*a ]]; then echo "Recipe for 2-branch block res2a"; else echo "Recipe for 1-branch block res2a"; fi
/bin/sh: 1: [[: not found
Recipe for 1-branch block res2a
rm -rf build_res2a
vivado_hls resblock.tcl -tclargs `if [[ res2a = res*a ]]; then echo 2; else echo 1; fi` res2a w1a2_v1.0 ip xcu250-figd2104-2L-e > build_res2a.log
/bin/sh: 1: [[: not found
Makefile:50: recipe for target 'res2a.zip' failed
make: *** [res2a.zip] Error 1
```
And I checked the log file build_res2a.log, there is some error in compiling process.
[build_res2a.log](https://github.com/Xilinx/ResNet50-PYNQ/files/4342473/build_res2a.log)

**Comment by quetric** [comment]
Hi @h-yuan 

It looks like your `/bin/sh` doesnt parse the conditional and incorrectly sets up the res2a build. Can you try using bash explicitly? E.g. `make NET=w1a2_v1.0 SHELL=/bin/bash`

**Comment by h-yuan** [comment]
Thanks for reply. The problem is solved by your instruction, and the reason is that the default shell is dash in ubuntu.
