### ISSUE TITLE
Ultra96-v2

### ISSUE THREAD

**Issue by oneyearold751** [Xilinx/ResNet50-PYNQ#7]
Hi, I want to run the code on Ultra96-v2. Is it possible? If possible, what should I revise? thank you

**Comment by quetric** [comment]
Hi,

The Zynq Ultrascale on the Ultra96 has too little internal memory for this design unfortunately. You need approximately 2500 18kbit Block RAMs (or equivalent storage capacity in Ultra RAM) to implement the Resnet50 as designed here.
